tests, fix h3 server check and parallel instances
curl/curl pull request #11553
Opened 2023-07-31 08:58 UTC by icing

- fix check for availability of nghttpx server
- add `tcp` frontend config for same port as quic, as without this, port 3000 is bound which clashes for parallel testing

2023-07-31 09:00 UTC, bagder approved these changes

2023-07-31 16:45 UTC, dfandrich requested changes
I've never installed nghttpx so I always ignored those error messages—sorry.

2023-07-31 16:45 UTC, dfandrich commented on tests/http3-server.pl
> +print "RUN: $cmdline\n" if($verbose or 1);
"or 1" looks like a debugging leftover

2023-08-01 08:35 UTC, icing commented on tests/http3-server.pl
> +print "RUN: $cmdline\n" if($verbose or 1);
Thanks for catching this!

2023-08-01 14:11 UTC, bagder approved these changes

2023-08-01 14:11 UTC, closed without merging