tool: avoid including leading spaces in the Location hyperlink
curl/curl pull request #11735
Opened 2023-08-25 18:09 UTC by mssdvd

This PR ensures that leading whitespaces are not marked as part of the Location URL.

Before:
![image](https://github.com/curl/curl/assets/18464329/6738286a-c25c-43f7-82c6-cf3cf346e99c)

After:
![image](https://github.com/curl/curl/assets/18464329/04aa3fd6-f654-42cf-8658-d38fb90e9fde)

2023-08-25 18:23 UTC, bagder commented on src/tool_cb_hdr.c
> +            finalurl, (int)prevllen, loc);
why should this use `prevllen` and not `locclen`? The first one includes whitespace and the latter does not.

2023-08-25 18:25 UTC, bagder commented
When I do `curl -I curl.se`, my terminal (Konsole) does not include the leading whitespace in the link.

2023-08-25 18:54 UTC, mssdvd commented
alacritty, foot and kitty include the space. I believe Konsole disables escape sequences for links by default.

2023-08-25 19:04 UTC, bagder commented
Ah, now I see the problem. Isn't this patch simpler?
~~~diff
diff --git a/src/tool_cb_hdr.c b/src/tool_cb_hdr.c
index aab96ae03..b1bad12e0 100644
--- a/src/tool_cb_hdr.c
+++ b/src/tool_cb_hdr.c
@@ -399,12 +399,12 @@ void write_linked_location(CURL *curl, const char *location, size_t loclen,
 
   if(!strcmp("http", scheme) ||
      !strcmp("https", scheme) ||
      !strcmp("ftp", scheme) ||
      !strcmp("ftps", scheme)) {
-    fprintf(stream, LINK "%s" LINKST "%.*s" LINKOFF,
-            finalurl, (int)loclen, location);
+    fprintf(stream, " " LINK "%s" LINKST "%.*s" LINKOFF,
+            finalurl, (int)loclen, loc);
     goto locdone;
   }
 
   /* Not a "safe" URL: don't linkify it */
 ~~~

> I believe Konsole disables escape sequences for links by default.

No it doesn't. At least I get it linkified just fine.

2023-08-25 19:06 UTC, bagder commented
Or maybe this is even better:
~~~diff
diff --git a/src/tool_cb_hdr.c b/src/tool_cb_hdr.c
index aab96ae03..878e8a563 100644
--- a/src/tool_cb_hdr.c
+++ b/src/tool_cb_hdr.c
@@ -399,12 +399,12 @@ void write_linked_location(CURL *curl, const char *location, size_t loclen,
 
   if(!strcmp("http", scheme) ||
      !strcmp("https", scheme) ||
      !strcmp("ftp", scheme) ||
      !strcmp("ftps", scheme)) {
-    fprintf(stream, LINK "%s" LINKST "%.*s" LINKOFF,
-            finalurl, (int)loclen, location);
+    fprintf(stream, " " LINK "%s" LINKST "%s" LINKOFF "\n",
+            finalurl, copyloc);
     goto locdone;
   }
 
   /* Not a "safe" URL: don't linkify it */

2023-08-25 19:07 UTC, bagder commented
/cc @dfandrich

2023-08-25 19:17 UTC, mssdvd commented
I had thought of fixing it like that. Is there a change that not specifying the length will lead to bugs?

2023-08-25 19:20 UTC, bagder commented
Not that I can spot since `copyloc` is null-terminated string it should be fine. But I still would like to get @dfandrich to chime in, he wrote this code.

2023-08-28 22:05 UTC, dfandrich commented
The original intention was to preserve the whitespace so the user gets the same output with or without styling enabled (modula the styling, of course). The proposed patch strips leading whitespace and replaces it with a single character, which is often, but not always, the same. I didn't bother eliminating the leading whitespace from the linked section, but I can see how it could be annoying on some terminals.

What I would probably do instead is count the amount of whitespace stripped in the `/* Strip leading whitespace of the redirect URL */` loop by adding a `++space_skipped` in the loop, then change the fprintf to:

```
    fprintf(stream, "%.*s" LINK "%s" LINKST "%.*s" LINKOFF,
             space_skipped, location, finalurl, (int)loclen - space_skipped, loc);
```

This is untested but the idea is to print the leading whitespace as-is, then the rest of the linkification without that leading space.

2023-08-28 23:23 UTC, dfandrich approved these changes
It works for me!

2023-08-28 23:46 UTC, dfandrich commented on src/tool_cb_hdr.c
>    while(llen && *loc == ' ') {
It turns out that HTTP allows a tab character here as whitespace as well, so that should also be skipped.

2023-08-28 23:47 UTC, dfandrich requested changes
skip tabs

2023-08-29 17:13 UTC, closed without merging

2023-08-29 17:13 UTC, dfandrich commented
Thanks!