file: make _wopen() and _open() able to handle long legacy DOS paths
curl/curl pull request #13512
Opened 2024-04-30 22:49 UTC by sergio-nsk

Issue: #8361

2024-05-01 02:55 UTC, jay commented
prepending `\\?\` to a path disables all parsing of the path. like any forward slashes and .. will not be converted. you are assuming that any path starting with the drive letter and a colon will not need any interpretation

2024-05-01 03:29 UTC, nmoinvaz commented
@jay that modified path is only passed into _open and _wopen. Are you seeing otherwise? As far as I can tell after it is used by those functions it is no longer used anywhere else.

2024-05-01 03:53 UTC, jay commented
> that modified path is only passed into _open and _wopen

I agree but I'm saying the logic is wrong. You can't assume that if a user specifies a path with a drive letter and colon that it is not going to need some interpretation. c:\foo/bar/../baz is not \\?\c:\foo/bar/../baz it is \\?\c:\foo\baz. you can't prepend \\?\ without first interpreting. Also IIRC \\?\ is only actually effective on the unicode W-suffixed api functions and crt w functions that wrap them (ie UNICODE/_UNICODE builds)

2024-05-01 04:42 UTC, sergio-nsk commented
> prepending `\\?\` to a path disables all parsing of the path. like any forward slashes and .. will not be converted. you are assuming that any path starting with the drive letter and a colon will not need any interpretation

Right, it disables the path parsing, but it does not matter, the limitation `PATH_MAX` breaks the file opening before the parse result that can be less than `PATH_MAX`. Hence, the result is the same unable to open a file.

The simple code with the existing 259 char path:
```c
#include <fcntl.h>
#include <io.h>
#include <stdio.h>
#include <string.h>

void win_open(const char *path, const char *msg)  {
   int fh1 = _open( path, _O_RDONLY ); // C4996
   // Note: _open is deprecated; consider using _sopen_s instead
   if(fh1 == -1) {
      printf("Open %s failed on file ", msg);
      perror("");
   } else {
      printf("Open %s succeeded on input file\n", msg);
      _close(fh1);
   }
}

int main(void) {
   const char *path259_l =   "\\\\?\\C:\\Work\\solid\\third_party\\curl\\tests\\log\\verylooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongdir\\dir\\..\\verylooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongfile3206.txt";
   const char *parsed259_l = "\\\\?\\C:\\Work\\solid\\third_party\\curl\\tests\\log\\verylooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongdir\\verylooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongfile3206.txt";

   win_open(path259_l + 4, "259 legacy");
   win_open(path259_l, "259 long");

   win_open(parsed259_l + 4, "259 parsed legacy");
   win_open(parsed259_l, "259 parsed long");
}
```
The output:
```
Open 259 legacy failed on file No such file or directory
Open 259 long failed on file Invalid argument
Open 259 parsed legacy succeeded on input file
Open 259 parsed long succeeded on input file
```

2024-05-01 04:53 UTC, sergio-nsk commented
As for forward slashes, curl translates them to backward slashes before `curlx_win32_open()` call.

2024-05-01 05:23 UTC, jay commented
> Right, it disables the path parsing, but it does not matter, the limitation `PATH_MAX` breaks the file opening before the parse result that can be less than `PATH_MAX`. Hence, the result is the same - unable to open a file.

It does matter. I think it's wrong to prepend `\\?\` without properly converting the path. Your logic assumes a long path (`wcslen(filename_w) >= MAX_PATH`) you can just prepend `\\?\` and that is not necessarily true.  Also IIRC there are still places in curl where we use PATH_MAX/MAX_PATH, as I mentioned in that other issue. You can't assume that all of libcurl code will successfully pass a long path to curlx_win32_open.

2024-05-01 05:35 UTC, sergio-nsk commented
> that is not necessarily true.

> You can't assume that all of libcurl code will successfully pass a long path to curlx_win32_open.

Not necessarily true, right. I don't assume anything. I just made it better in some cases, and not worse in other cases.

2024-05-02 08:11 UTC, bagder requested changes
The new test fails in several windows CI jobs.

2024-05-03 01:52 UTC, sergio-nsk commented
MinGW builds don't seem to translate / to \ file paths. Will loot for the best solution, maybe just will just replace / with \ in the changed function.

2024-05-03 07:54 UTC, jay commented
I'm proposing #13522 to address this issue with a normalization check and cover all the file functions that we wrap.

2024-05-04 02:40 UTC, sergio-nsk commented
I will check https://github.com/curl/curl/pull/13522 in WinRT on Monday. Long paths are usual in WinRT.

2024-05-06 16:38 UTC, sergio-nsk commented
Closing in favor of the other PR.

2024-05-06 16:38 UTC, closed without merging