multi: fix timing metrics on connect failure
curl/curl pull request #14204
Opened 2024-07-16 22:53 UTC by jmaggard10

On platforms without AsynchDNS, if name resolution fails for a transaction, CURLINFO_TOTAL_TIME (and all other timing metrics) return 0, which is rather misleading.

This commit adds a final Curl_pgrsUpdate() call before returning to update the timing metrics.

2024-07-18 13:17 UTC, bagder approved these changes

2024-07-18 18:02 UTC, dfandrich commented
Analysis of PR #14204:

[Test 1268 failed](https://github.com/curl/curl/actions/runs/9965217539),
which has NOT been flaky recently, so **there could be a real issue in the PR**.
Note that this test has failed in 70 different CI jobs (the link just goes to one of them).

[Test 1471 failed](https://github.com/curl/curl/actions/runs/9965217539),
which has NOT been flaky recently, so **there could be a real issue in the PR**.
Note that this test has failed in 70 different CI jobs (the link just goes to one of them).

[Test 1472 failed](https://github.com/curl/curl/actions/runs/9965217539),
which has NOT been flaky recently, so **there could be a real issue in the PR**.
Note that this test has failed in 70 different CI jobs (the link just goes to one of them).

###### Generated by [Testclutch](https://testclutch.curl.se/)

2024-07-18 18:04 UTC, dfandrich commented
Several tests aren't expecting to see progress output in their stderr, so those should be updated to add --no-progress-meter or similar.

2024-07-18 21:23 UTC, bagder requested changes
Test fails need attention

2024-07-19 22:30 UTC, jmaggard10 commented
Tests fixed and passing now.

2024-07-19 22:32 UTC, bagder approved these changes

2024-07-19 22:35 UTC, bagder commented
Hm, I'm having second thoughts about this. It might upset a few people as it now (uslessly) outputs that progress bar in failure cases is never did before...

2024-07-19 22:49 UTC, bagder commented
I propose #14239 instead. It should get the same effect but without the progress callback/meter update.

2024-07-19 22:51 UTC, jmaggard10 commented
Sounds good to me, thanks.

2024-07-20 15:11 UTC, closed without merging