ssl: Fix compilation with OpenSSL 1.x with md4 disabled
curl/curl pull request #14218
Opened 2024-07-18 04:47 UTC by orgads

If OpenSSL 1.x is used, and it is configured with md4 disabled, OPENSSL_NO_MD4 is defined in opensslconf.h, but this header was not included before checking for this define.

Later in md4.c, openssl/md4.h is included, and it includes that header indirectly, leading to inconsistency within md4.c.

Since the md4.h branch was taken, wincrypt.h (or others) is not included, and later below the USE_WIN32_CRYPTO branch is taken, but the types are not defined.

2024-07-18 06:42 UTC, orgads commented
Is the failing test known to be flaky? What exactly failed there?

2024-07-18 08:12 UTC, vszakats commented
Yes, _all_ native tests are flaky.

2024-07-18 08:32 UTC, orgads commented
> Yes, _all_ native tests are flaky.

So should I rerun it? How?

2024-07-18 13:17 UTC, bagder approved these changes

2024-07-18 17:15 UTC, MarcelRaad commented
> So should I rerun it? How?

You can click on the job that failed, and then on "re-run failed jobs" in the menu at the top. I just did that, and enabled debug logging as there was no output at all for the tests, only the failure mark.

2024-07-18 17:18 UTC, MarcelRaad approved these changes
Nit: this is done in an `#else` branch for other backends.

2024-07-18 21:35 UTC, bagder requested changes
Ah yes, using an `#else` there as mentioned by @MarcelRaad makes sense.

2024-07-19 06:15 UTC, orgads commented
Done

2024-07-19 16:27 UTC, bagder approved these changes

2024-07-19 16:27 UTC, closed without merging

2024-07-19 16:27 UTC, bagder commented
Thanks!