fix openssl Channelbinding
curl/curl pull request #14294
Opened 2024-07-29 07:48 UTC by fengyue520

2024-07-29 08:23 UTC, bagder commented
Thanks for helping out. Do try `make checksrc` to verify that your used code style matches the requirements!

2024-07-31 21:26 UTC, bagder requested changes

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +  ZeroMemory(context_bindings, sizeof(SecPkgContext_Bindings));
If you really need the newly allocated memory to be cleared, then use calloc() instead of malloc(). No need to call an extra function.

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +  context_bindings = (SecPkgContext_Bindings*)malloc(sizeof(SecPkgContext_Bindings));
malloc can fail, you need to handle that

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +  channel_bindings = (SEC_CHANNEL_BINDINGS*)malloc(context_bindings->BindingsLength);
malloc is fallible again

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +  ZeroMemory(channel_bindings, context_bindings->BindingsLength);
and use calloc() again

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +  ZeroMemory(certificate_hash, sizeof(certificate_hash));
Why? it gets populated below, does it not?

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +  strcpy((char*)channel_binding_token, TLS_SERVER_END_POINT);
This strcpy() looks... a bit shaky. How can we guarantee that this is within the allocated buffer?

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +  CopyMemory(&channel_binding_token[prefix_length], certificate_hash, certificate_hash_length);
is this `memcpy`  ?

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +SecPkgContext_Bindings* tls_get_channel_bindings(X509* cert)
```suggestion
static SecPkgContext_Bindings* tls_get_channel_bindings(X509* cert)
```

2024-07-31 21:26 UTC, bagder commented on lib/vtls/openssl.c
> +CertSignatureAlgorithm get_signature_algorithm(const X509* cert) {
```suggestion
static CertSignatureAlgorithm get_signature_algorithm(const X509* cert) {
```

2024-12-18 04:22 UTC, jay commented
No response, closing.

2024-12-18 04:22 UTC, closed without merging