tests: improve test_17_07_ssl_ciphers
curl/curl pull request #14589
Opened 2024-08-19 02:24 UTC by jan2000

Change TLS proto version on the test server to test setting combinations of --tls13-ciphers and --ciphers.

Overloading of autouse fixtures does not seem to work. For the test httpd server to be reloaded with a clean config in test_18_methods, to not be affected by the config changes in test_17_ssl_use, the two class scope fixtures of test_18_methods are now combined.

Added return value to set_extra_config and clear_extra_configs to indicate changes, making it possible to prevent unnecessarily reloading of the test httpd server.

2024-08-19 02:41 UTC, jan2000 commented
@icing especially notice the part about the double `_class_scope`. These are also in other pytest classes. Maybe I misunderstand it, but it seems these need to be fixed as well.

2024-08-19 07:06 UTC, icing requested changes

2024-08-19 07:06 UTC, icing commented on tests/http/testenv/httpd.py
> +        if domain not in self._extra_configs:
The name `set_extra_confg` was intended to replace. If you need an `add_extra_config` it would be better to make that a new method.

2024-08-19 07:06 UTC, icing commented on tests/http/test_18_methods.py
> +            httpd.reload()
good catch!

2024-08-20 01:20 UTC, jan2000 commented
The previous method of preventing unnecessarily reloading of the test httpd server did not properly prevent bleeding of config into the next test. Changed to other method.

2024-08-20 06:42 UTC, icing approved these changes

2024-08-20 10:46 UTC, closed without merging