openssl: do not break HTTP proxy due to missing TLS channel binding
curl/curl pull request #15410
Opened 2024-10-25 04:17 UTC by Foorack

Fixes https://github.com/curl/curl/issues/14973

I want to avoid breaking past working functionality, so I have made a proposed PR which - similar to if a peer certificate isn't presented - soft-fails and continues establishing the connection without SecureChannelBinding even if an SSL backend isn't found (such as when using a HTTP proxy).

This makes the **_behaviour_** of CURL the same as before then SCB feature was integrated.

And then if someone very specifically needs SecureChannelBinding over HTTP proxy (if that is even technically possible!?) it could be implemented in a future request.

2024-10-25 07:02 UTC, vszakats requested changes

2024-10-25 07:02 UTC, vszakats commented on lib/vtls/openssl.c
> +      return CURLE_OK;
```suggestion
    /* No SSL backend, don't do channel binding */
    return CURLE_OK;
```

2024-10-25 07:15 UTC, bagder commented
I don't see how returning ok when the connection can't be found can be correct for this case? The connection is using TLS, it's just done over a proxy.

2024-12-23 22:09 UTC, bagder commented
Abandoned

2024-12-23 22:09 UTC, closed without merging