Make configure fail when requested lib missing.
curl/curl pull request #6598
Opened 2021-02-12 01:15 UTC by jsha

If --with-hyper or --with-rustls is specified, it should be an error to
not find the corresponding library.

2021-02-12 07:23 UTC, bagder approved these changes

2021-02-12 10:01 UTC, bagder reviewed
Hm, this isn't sufficient as it seems we run through this condition when the option isn't even specified so this change causes build failures. [example](https://dev.azure.com/daniel0244/curl/_build/results?buildId=4699&view=logs&j=9d58b9ac-e1e6-53b6-f83a-1f9f1d912522&t=9c6369fd-15c1-5199-409e-298db1d36c77&l=308)

2021-02-12 10:02 UTC, bagder requested changes
breaks the build

2021-02-12 17:42 UTC, jsha commented
I had assumed the ./configure behavior was not to try hyper unless `--with-hyper` was passed, but looking again I see that the behavior is actually to try always look for hyper and use it if the library is available. What do you think of changing that, so building with hyper requires the `--with-hyper` flag?

Rationale: I was trying to build with Hyper yesterday, and was having trouble getting it configured correctly. I needed to make sure to build with the right feature flags and the right RUSTFLAGS, and put it in the right place, and set up LD_LIBRARY_PATH and CFLAGS=-L/usr/local/lib. That's all fine: part of the software life. But my debugging cycles were longer than necessary, because if my Hyper install was broken, `./configure --with-hyper` would happily continue and set up curl without Hyper. Given that Hyper is still experimental, it seems sensible to require both the flag and the library install to turn it on. That would enable us to treat OPT_HYPER=yes as a stronger signal of user intent.

2021-02-14 10:02 UTC, bagder commented
> I had assumed the ./configure behavior was not to try hyper unless `--with-hyper` was passed, but looking again I see that the behavior is actually to try always look for hyper and use it if the library is available. What do you think of changing that, so building with hyper requires the `--with-hyper` flag?

I think it was a mistake. I think we *should* require the  `--with-hyper` flag for a hyper build. In particular because the backend is still marked experimental but also because I think users expect it to behave that way!

2021-02-18 04:27 UTC, jsha commented
Updated the change (including PR title and description) based on the conversation above.

2021-02-22 22:21 UTC, bagder approved these changes

2021-02-23 06:39 UTC, bagder commented
Thanks!

2021-02-23 06:39 UTC, closed without merging