libssh: enforce semicolons when using macros
curl/curl pull request #6848
Opened 2021-04-04 11:23 UTC by emilengler

This enforces the usage of semicolons when using CPP macros. We
currently use semicolons anyway, however this leads to certain warnings
on certain compilers.

Fixes #6847

2021-04-04 21:59 UTC, bagder approved these changes

2021-04-05 05:41 UTC, jay commented
` T=normal C=--with-libssh` failed and the restart button is gone so I can't restart it. @bagder does the restart button show for you

2021-04-05 09:52 UTC, bagder commented
It showed. I pressed!

2021-04-05 10:44 UTC, bagder commented
We get segfaults. [example](https://travis-ci.org/github/curl/curl/jobs/765822308#L3512)

2021-04-05 10:46 UTC, bagder requested changes

2021-04-05 10:46 UTC, bagder commented on lib/vssh/libssh.c
> +} while(0)
This macro now puts the break inside the do-while so it won't break out from the switch like before, changing the flow significantly... I would suggest you remove the break from the macro and write it outside of it in the code - which I think also increases code readability.

2021-04-06 14:45 UTC, emilengler commented
I adjusted @bagder, now lets wait for the CIs

2021-04-06 14:48 UTC, bagder commented
You need to adjust all those macros, as they all use `break`...

2021-04-06 14:58 UTC, emilengler commented
Done

2021-04-06 16:05 UTC, bagder commented
This works. I still think you should work on moving the breaks out from the macros and into the code though. I don't like how the breaks inside the macros makes the code not really possible follow. I spotted at least one use of a `MOVE_TO_*` macro within a loop, which then presumably might not work the way the macro is intended but it is really hard to see in the code as written right now.

2021-04-06 16:14 UTC, emilengler commented
> This works. I still think you should work on moving the breaks out from the macros and into the code though. I don't like how the breaks inside the macros makes the code not really possible follow. I spotted at least one use of a `MOVE_TO_*` macro within a loop, which then presumably might not work the way the macro is intended but it is really hard to see in the code as written right now.

Oh that was what you meant! Sure let me do.

2021-04-06 21:56 UTC, bagder commented
Yeah, it's a slightly bigger change but I believe the result might also be a bigger improvement.

2021-04-16 10:52 UTC, emilengler commented
I don't see myself able to fix this short-time as of now (due to lack of time). Will close this and might come back to it later

2021-04-16 10:52 UTC, closed without merging