Fix HTTP/3 bug: uploading payload larger than 65536 will be blocked until timeout.
curl/curl pull request #7538
Opened 2021-08-06 07:47 UTC by MegatronKing

The upload buffer default size is 65536, if we post a payload larger than this, the first buffer is ok, but when sending the second buffer, the stream will be blocked with a curlcode CURLE_AGAIN. I supoose the cause is the upload_len was not reset.RARY

2021-08-06 21:11 UTC, bagder commented on lib/vquic/ngtcp2.c
> +  // Reset post upload buffer after resumed.
This style of comment is not allowed in curl code as its not C89 compliant! Use /* */ ...

2021-08-08 20:50 UTC, bagder requested changes

2021-08-08 20:50 UTC, bagder commented on lib/vquic/ngtcp2.c
> +  if(data->set.postfields) {
This seems too specific for POST. Shouldn't this rather check if `stream->upload_mem` is set?

2021-08-10 07:50 UTC, bagder commented
and the other comment, what do you think about it?

2021-08-10 08:32 UTC, MegatronKing commented
@bagder 
Actually, I am not very confident about my fix, I tested with all my POST cases and all approved.
I am confusing about the function 'cb_h3_readfunction', when and how it would be invoked? And this line https://github.com/curl/curl/blob/b836b065bd6598a8c549863825fcfcd0306b3cb5/lib/vquic/ngtcp2.c#L1350 also is specific for POST and I am not able to understand too.

2021-08-10 08:37 UTC, MegatronKing commented
My test cases:
- POST application/octem 10/100/1024/1024 * 1024/10 * 1024 * 1024
- POST multipart/form-data 10/100/1024/1024 * 1024/10 * 1024 * 1024
And something intersting, POST  multipart/form-data and _data->set.postfields_ is false.

2021-08-10 08:57 UTC, bagder commented
> POST multipart/form-data and data->set.postfields is false

That's why I didn't like the fix. `set.postfields` is only set with `CURLOPT_POSTFIELDS`  while you can send data over HTTP several other ways with libcurl. One of those ways you see. You can also try `curl -T [file] -X POST $URL` ...

So if you make the change I proposed, does it still work or isn't that good enough?

2021-08-10 09:26 UTC, MegatronKing commented
if data->set.postfields is true, a flag NGHTTP3_DATA_FLAG_EOF is set and return, and the value of stream->upload_len would never be updated, right? I think this is a bug.

2021-08-10 09:42 UTC, MegatronKing commented
Agree with the fix is not good enough, I updated!

2021-08-10 14:46 UTC, bagder approved these changes

2021-08-10 14:58 UTC, bagder commented
do you have a HTTP/3 test server somewhere that you can do large posts to, to verify this fix?

2021-08-10 21:10 UTC, closed without merging

2021-08-10 21:11 UTC, bagder commented
Thanks, I pushed this as I believe it does improve things. I still experience problems if I upload multiple megabytes, but after all the data has been sent...