remove requirement on HAVE_SYS_UN_H for unix domain sockets on Windows
curl/curl pull request #7737
Opened 2021-09-17 12:57 UTC by mzr

As described in #5162 curl with option `--unix-socket` on Windows was failing with:
```
* sa_addr inet_ntop() failed with errno 10047: Address family not supported
```

It happened because in `Curl_addr2string`'s switch statement, case with `AF_UNIX` was behind `define(HAVE_SYS_UN_H) && defined(AF_UNIX)`. There is no `sys/un.h` on Windows. On Windows `sockaddr_un` is defined in `afunix.h` (not in `sys/un.h` as it's on unix-like OSs). After this change, curl with `--unix-socket` worked for me as expected.

I'm not sure if this is the proper way to fix this, so I'd welcome some feedback. Also, I'm counting on tests that should run on this PR to see if things are OK.

2021-09-17 14:58 UTC, bagder approved these changes
:+1:

2021-09-17 15:49 UTC, bagder commented
It seems not be quite true [everywhere](https://github.com/curl/curl/pull/7737/checks?check_run_id=3632444705):
~~~
connect.c: In function 'Curl_addr2string':
connect.c:663:48: error: invalid use of undefined type 'struct sockaddr_un'
  663 |         msnprintf(addr, MAX_IPADR_LEN, "%s", su->sun_path);
      |                                                ^~

2021-09-19 10:31 UTC, mzr commented
I'll take a look into that. I'm guessing there is a mismatch between different toolchains/compilers? I'm not very familiar with Windows world :/ Also I might have had wrong compilation options (or just missing something) when I was compiling it myself on my machine - I was just using [this](https://github.com/alexcrichton/curl-rust/blob/master/curl-sys/build.rs) as is. However, I think this might be unlikely as `HAVE_SYS_UN_H` seems like it's required for unix sockets to work and doesn't seem to have much sense on Windows.

2021-09-19 11:39 UTC, gvanem commented
>  I'm guessing there is a mismatch between different toolchains/compilers?

The MinGW I have (TDM-gcc 8.0.0) have `AF_UNIX` defined in it's `winsock*.h`. But no `struct sockaddr_un` anywhere.
So maybe this somewhere:
```c
#if !defined(HAVE_SOCKADDR_UN)
struct sockaddr_un {
       sa_family_t sun_family;   
       char        sun_path [200];
     };
#endif
```

2021-09-19 22:15 UTC, mzr commented
Hmm, I see there is something similar already in the code [here](https://github.com/curl/curl/blob/master/lib/curl_setup.h#L829-L843).

2021-09-19 23:18 UTC, mzr commented
Ahh this doesn't seem to do the trick as well. I think it might work but only with cmake build.

2021-09-20 00:07 UTC, mzr commented
I added a little change, so it should now work not only with cmake.

2021-09-21 07:52 UTC, bagder requested changes

2021-09-21 07:52 UTC, bagder commented on lib/connect.c
> +#if defined(HAVE_SOCKADDR_UN) && defined(AF_UNIX)
`HAVE_SOCKADDR_UN` is only set in cmake and Windows builds, excluding all the configure builds!

2021-09-29 06:43 UTC, mzr commented
I changed it to something much simpler. It should work for all cases and builds where it previously worked and for cases where sockaddr_un is manually defined on Windows in `curl_setup.h`. Might not be perfect, but it's still an improvement.
Tests that are failing I believe are not related.

2021-09-29 10:27 UTC, mzr commented
rebased

2021-09-30 08:58 UTC, bagder approved these changes

2021-09-30 10:28 UTC, bagder commented
Thanks!

2021-09-30 10:28 UTC, closed without merging