CURLOPT_HAPROXYPROTOCOLV2: add support for the HAProxy PROXY protocol v2
curl/curl pull request #8205
Opened 2022-01-01 21:35 UTC by remilapeyre

Add --haproxy-protocol-v2 for the command line tool

2022-01-01 21:38 UTC, bagder commented
How about instead extending `CURLOPT_HAPROXYPROTOCOL` to accept either a bitmask or multiple values? The current (old) behavior accepts a '1' for protocol version 1, so it is perfectly possible to use '2' for version 2!

2022-01-01 21:43 UTC, bagder commented on docs/libcurl/symbols-in-versions
> +CURLOPT_HAPROXYPROTOCOL         7.81.0
Typo (missing v2) and plan for 7.82.0!

2022-01-01 23:04 UTC, remilapeyre commented
> How about instead extending `CURLOPT_HAPROXYPROTOCOL` to accept either a bitmask or multiple values? The current (old) behavior accepts a '1' for protocol version 1, so it is perfectly possible to use '2' for version 2!

Just to be sure: we are only talking about the way the implementation, not the cli interface? If thought about this but wasn't sure whether we could change CURLOPT_HAPROXYPROTOCOL from a  bit to a bitmask.

In any case, we would still have multiple flag on the command line to choose the PROXY protocol version `--haproxy-protocol` and `--haproxy-protocol-v2` right? I initially wanted to make it possible to use `--haproxy-protocol`, `--haproxy-protocol=v1` and `--haproxy-protocol=v2` but it seems to me that this is not possible.

If you confirm that my understanding is correct I will update the patch to do this.

2022-01-01 23:16 UTC, bagder commented
Yes. You can add this without adding a new libcurl option. You cannot avoid a new command line option-

2022-01-02 01:17 UTC, remilapeyre commented
Thanks for the feedback @bagder, here's a new version that only uses `CURLOPT_HAPROXYPROTOCOL`.

2022-01-02 12:22 UTC, bagder commented on lib/setopt.c
> +     * Set to send the HAProxy Proxy Protocol v1 header
It's not just "v1" now...

2022-01-02 12:22 UTC, bagder commented on lib/setopt.c
> +    data->set.haproxyprotocol = va_arg(param, long);
Please make this return an error if an unsupported value is set.

2022-01-02 12:22 UTC, bagder commented on src/tool_getparam.c
> +        config->haproxy_protocol = 2L;
Maybe `warnf()` if one protocol version option overwrites a previously set protocol option?

2022-01-02 12:22 UTC, bagder commented on lib/http.c
> +        },
How about making this chunk a `const static` array instead? Will also make it slightly more readable I think.

2022-01-02 12:22 UTC, bagder commented on lib/http.c
> +      16
and then you could use `sizeof()` here instead of a magic constant

2022-01-02 12:22 UTC, bagder commented on lib/urldata.h
> +  long haproxyprotocol; /* whether to send HAProxy PROXY protocol header */
1. You could save a few bytes by not storing this as a `long`.
2. Move this field declaration to above the `BIT()` fields to better use struct space.

2022-01-02 12:22 UTC, bagder commented on docs/cmdline-opts/haproxy-protocol-v2.d
> +Added: 7.81.0
7.82.0

2022-01-02 12:24 UTC, bagder commented
> `--haproxy-protocol-v2 is in the option directory but not in ./../docs/options-in-versions!`

Meaning that you need to amend `docs/options-in-versions` with info about this new option.

2022-01-10 22:13 UTC, remilapeyre commented
Hi @bagder, here's a new version that should address all your comments.

2022-01-11 10:15 UTC, bagder commented
~~~
http.c: In function ‘add_haproxy_protocol_header’:
http.c:1545:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 1545 |   static const char binaryheader[] = {
      |   ^~~~~~
cc1: all warnings being treated as errors

2022-01-13 09:24 UTC, bagder requested changes

2022-01-13 23:38 UTC, remilapeyre commented
Hi @bagder, I tried to fix all issues. I'm a bit confused why some test fail though.

2022-01-15 20:40 UTC, bagder commented
Did you actually get those two new tests to work without having to modify the test server?

2022-01-15 22:19 UTC, bagder commented
Also, I would advice you use the `%hex[` construct to add binary data into the tests to compare with. Similar to this:
~~~
<protocol>
%hex[ 0d 0a 0d 0a 00 0d 0a 51 55 49 54 0a 20 00 00 00 ]hex%GET /%TESTNUMBER HTTP/1.1
Host: %HOSTIP:%HTTPPORT
User-Agent: curl/%VERSION
Accept: */*
Testno: %TESTNUMBER
~~~

2022-01-15 22:22 UTC, bagder commented
Gah, sorry I messed up that commit. I'll force-push a cleanup

2022-01-15 22:23 UTC, bagder commented
Sorry for that. I just wanted to fix the copyright year ranges for you. :disappointed:

2022-01-15 23:18 UTC, bagder commented
I think I fixed the tests and test server to do right so that you can verify that curl sends the right data.

Doing this and checking the proxy protocol spec, I have questions though:

The code says `/* protocol is UNSPEC */` (and this is verified by the tests) - but why? The spec says that should be used "for an unknown, unspecified or unsupported protocol". This is neither unknown nor unsupported. We know that it is IPv4, IPv6 or a unix domain socket. So why doesn't this pass on the addresses, just like does for v1?

2022-01-15 23:45 UTC, remilapeyre commented
> I think I fixed the tests and test server to do right so that you can verify that curl sends the right data.
> 

Thanks for taking care of this.

> Doing this and checking the proxy protocol spec, I have questions though:
> 
> The code says `/* protocol is UNSPEC */` (and this is verified by the tests) - but why? The spec says that should be used "for an unknown, unspecified or unsupported protocol". This is neither unknown nor unsupported. We know that it is IPv4, IPv6 or a unix domain socket. So why doesn't this pass on the addresses, just like it does for v1?

Yes this is different than what it does for v1. I'm not well versed in what must be done here and I think it depends on the context, for example if cURL is being used to test a connection, or used to send health-checks or used to connect on behalf of a client.

In my case I would like to be able to use `curl --haproxy-protocol-v2 ...` to test a connection, other users might need more knobs. Here's my understanding:

 - for v1 https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt section 2.1. says:

>  For "UNKNOWN", the rest of the line before the
>    CRLF may be omitted by the sender, and the receiver must ignore anything
>   presented before the CRLF is found. Note that an earlier version of this
>   specification suggested to use this when sending health checks, but this
>    causes issues with servers that reject the "UNKNOWN" keyword. Thus is it
>    now recommended not to send "UNKNOWN" when the connection is expected to
>    be accepted, but only when it is not possible to correctly fill the PROXY
>    line.

so the current behavior for v1 seems correct to me.

- for v2 section 2.2 says:

> The lowest four bits represents the command :
>   - \x0 : LOCAL : the connection was established on purpose by the proxy
>     without being relayed. The connection endpoints are the sender and the
>     receiver. Such connections exist when the proxy sends health-checks to the
>     server. The receiver must accept this connection as valid and must use the
>     real connection endpoints and discard the protocol block including the
>     family which is ignored.

which I think is the case that matters here. The rest of the header is therefore set:

> The address family maps to the original socket family without necessarily
> matching the values internally used by the system. It may be one of :
>  
>   - 0x0 : AF_UNSPEC : the connection is forwarded for an unknown, unspecified
>     or unsupported protocol. The sender should use this family when sending
>     LOCAL commands or when dealing with unsupported protocol families. The
>     receiver is free to accept the connection anyway and use the real endpoint
>     addresses or to reject it. The receiver should ignore address information.



and 

> The transport protocol is specified in the lowest 4 bits of the 14th byte :
> 
>   - 0x0 : UNSPEC : the connection is forwarded for an unknown, unspecified
>     or unsupported protocol. The sender should use this family when sending
>     LOCAL commands or when dealing with unsupported protocol families. The
>     receiver is free to accept the connection anyway and use the real endpoint
>     addresses or to reject it. The receiver should ignore address information.
 
so in my case I think everything needs to be set as `UNSPEC`.

2022-01-16 16:46 UTC, bagder commented
> Yes this is different than what it does for v1.

That's exactly why I have a really hard time to understand and accept it. Why would the use case be different and much more limited just because you change to v2? To me, the protocol seems to be almost pointless if you don't actually provide any information in there. The intended purpose of the protocol is one and the same for both protocol versions. They're just a different ways to send the data (readable vs binary).

Put another way: is there a good reason to *not* provide the IP information?

2022-02-21 07:52 UTC, bagder commented
I cannot accept this PR as it is only half-baked and nobody works on it.

2022-02-21 07:52 UTC, closed without merging