configure: set CURL_LIBRARY_PATH for nghttp2
curl/curl pull request #8340
Opened 2022-01-27 17:42 UTC by bwncp

To execute the test program, we might need the library path so that the lib is found at runtime.

2022-01-27 21:33 UTC, bagder requested changes
Setting the variable seems like the right change indeed, but I think it should be done slightly further down, in the code block where `USE_NGHTTP2` is set. Because otherwise you might have it set before it is confirmed to be the right version.

2022-01-28 11:08 UTC, bwncp commented
> Setting the variable seems like the right change indeed, but I think it should be done slightly further down, in the code block where `USE_NGHTTP2` is set. Because otherwise you might have it set before it is confirmed to be the right version.

Thanks for your feedback. 

Fixed now.

2022-01-28 14:51 UTC, bagder approved these changes

2022-01-28 14:55 UTC, bagder commented
Thanks!

2022-01-28 14:55 UTC, closed without merging