cookies: Improve errorhandling for reading cookiefile
curl/curl pull request #8699
Opened 2022-04-12 11:58 UTC by danielgustafsson

The existing programming had some issues with errorhandling for reading
the cookie file. If the file failed to open, we would silently ignore it
and continue as if there was no file (or stdin) passed. In this case, we
would also call fclose() on the NULL FILE pointer, which is undefined
behavior. Fix by ensuring that the FILE pointer is set before calling
fclose on it, and error out in case the cookiefile cannot be opened.

Closes: #xxxx

2022-04-13 10:01 UTC, danielgustafsson commented
Erroring out on nonexisting cookiefile is too invasive to backwards compat, so let's not go there.

2022-04-14 21:57 UTC, bagder approved these changes

2022-04-15 07:21 UTC, jay requested changes

2022-04-15 07:21 UTC, jay commented on lib/cookie.c
> +  else if((file && !*file) || (!file)) {
```suggestion
  else if(!file || !*file) {
```

2022-04-15 07:21 UTC, jay commented on lib/cookie.c
> +  else if(file) {
this is always going to be true because of block above

2022-04-15 07:21 UTC, jay commented on lib/cookie.c
>    else
this is unreachable because of block above

2022-04-15 21:50 UTC, danielgustafsson commented
@jay thanks, fixed up with your comments.

2022-04-16 04:25 UTC, jay commented on lib/cookie.c
> +    if(fromfile && fp)
this statement is in block if(fp) so you can skip the check here

2022-04-20 13:02 UTC, closed without merging