runtests: convert protocol to CRLF on Windows
curl/curl pull request #9254
Opened 2022-08-05 10:19 UTC by orgads

The protocol field is saved as binary (the rest of the file is LF but
this part is CRLF). It is overwritten by both VS Code and Qt Creator,
that replace it with LF to match the rest, and this breaks the tests.

2022-08-05 10:22 UTC, orgads commented
Actually this should not be Windows-specific, as it will break on other platforms if tests file are rewritten with LF.

How about adding something like `eol="lf"` attribute to `<protocol>` (default to `crlf`), and translate according to this attribute?

2022-08-06 06:28 UTC, emilengler commented
> It is overwritten by both VS Code and Qt Creator, that replace it with LF to match the rest, and this breaks the tests.

This is not our fault.

2022-08-06 15:23 UTC, bagder requested changes
This is a big no-no. The protocol needs to be checked *binary* and your system clearly broke the tests if it modified the newlines. Stop it from doing that.

2022-08-06 15:30 UTC, closed without merging

2022-08-06 18:38 UTC, orgads commented
How about my other suggestion in the comment? https://github.com/curl/curl/pull/9254#issuecomment-1206290093

How do you edit the test files?

2022-08-06 18:56 UTC, emilengler commented
> How about my other suggestion in the comment? https://github.com/curl/curl/pull/9254#issuecomment-1206290093
> 
> 
> 
> How do you edit the test files?

I personally use a combination of vi and emacs.

2022-08-06 20:31 UTC, orgads commented
Having different newlines in a single file is *very* odd. I've never seen anything like it, especially when the content is XML, so it's text anyway. Why not use a markup for the line endings, and handle it in the runner script?

2022-08-06 21:38 UTC, bagder commented
> Why not use a markup for the line endings, and handle it in the runner script?

Mostly because

1. it has not been a problem
2. it would require changing some 1500+ files

2022-08-06 21:48 UTC, orgads commented
1. How many developers contribute tests? Am I the first to hit this issue?
2. It is very easy to write a script that will adapt all the files if you agree to this change.

2022-08-06 21:53 UTC, bagder commented
> How many developers contribute tests? Am I the first to hit this issue?

~~~
git shortlog -s -- tests | wc -l
220
~~~

> It is very easy to write a script that will adapt all the files if you agree to this change.

I would be open to the idea, but it depends on the exact change.