cookies: optimize control character check
curl/curl pull request #9736
Opened 2022-10-14 22:40 UTC by danielgustafsson

When checking for invalid octets the `strcspn()` call will return the position of the first found invalid char or the first `NULL` byte. This means that we can check the indicated position in the search- string saving a `strlen()` call.

2022-10-16 06:00 UTC, jay requested changes

2022-10-16 21:40 UTC, bagder commented on lib/cookie.c
> +  return (p[len] == '\0');
The one-liner is a bit harder to read though...

2022-10-17 04:34 UTC, jay commented on lib/cookie.c
> +  return (p[len] == '\0');
p[len] != '\0' is fine with me

2022-10-21 11:34 UTC, danielgustafsson commented on lib/cookie.c
> +  return (p[len] == '\0');
> I think you meant !=

I did, that was an uncaffeinated typo. Fixed in rebased patch.

2022-10-21 13:51 UTC, danielgustafsson commented
Skimming the testing errors they (so far) seem unrelated to the diff in question.

2022-10-24 04:51 UTC, jay approved these changes

2022-10-24 09:32 UTC, closed without merging