curl: don't ignore query part when using --remote-name
curl/curl pull request #9845
Opened 2022-11-02 21:50 UTC by martinwhitaker

PR #9684 changed the behaviour of --remote-name to ignore the possible query part of the URL when generating the output file name. This breaks existing code that use curl and expect the old behaviour. This update restores the original behaviour whilst still using the URL parser.

Fixes #9826

2022-11-03 07:51 UTC, bagder approved these changes
I don't like it but I understand why we need to do this.

2022-11-03 07:54 UTC, bagder commented
Did we convert the question mark on Windows before to make it work there?

2022-11-03 07:55 UTC, bagder requested changes
test fails on Windows

2022-11-03 13:04 UTC, martinwhitaker commented
I've fixed the test to work on Windows. The call to `sanitize_file_name` was there before PR #9684, so the question mark would have been converted.

There are still a few failing tests, but they don't appear to be be related to this PR.

2022-11-03 23:31 UTC, vszakats commented
I think curl stripping query params from the filename is the _expected_ (least surprise) behaviour here (saying this after having to rename unexpectedly mangled filenames way too many times). I also understand it may break compatibility if someone is actually building on this unexpected behaviour. Can we reconsider reverting this or implementing some other solution? Or maybe wait a bit to see if this causes widespread breakage?

2022-11-03 23:56 UTC, martinwhitaker commented
Well, this has broken the Mageia installler and package manager (urpmi) and is blocking the alpha release of Mageia 9. Is that widespread enough?

And I don't consider stripping the query is the least surprising behaviour. A different query will normally result in different data being returned, so it makes sense to me to store it in a different file.

wget will similarly include the query part in the saved file name.

2022-11-04 00:35 UTC, vszakats commented
Can't speak for `urpmi` specificially, but perhaps there is a reasonable way to update the affected script to not rely on this specific behaviour (and making it work with both 7.86.0 and earlier versions). Also, 7.86.0 is out already, so scripts encountering this version will need to adapt for it, unless they have a way to force a specific earlier (or later?) curl version.

I'm for collecting a bit more data points before reverting.

2023-01-21 02:20 UTC, Smackd0wn commented
The "original behaviour" prior to 7.86.0 also included the fragment part in the filename. For example,

`curl -O "https://example.com/index.html#[1-10]"`  (adapted from [ref.](https://daniel.haxx.se/blog/2022/12/23/the-curl-fragment-trick/))

would produce output `index.html#1` to `index.html#10`. But that behaviour is not restored by this patch. According to Hyrum's law, that must also break some people's workflow. Should that be reverted as well?


While we're at it, I'd say URL-decoded filename would be the "least surprising behaviour" (wget also does it). But that's another story, and I think "do not break existing scripts and applications" is one of the core principles of curl ([ref.](https://daniel.haxx.se/blog/2022/09/08/http-http-http-http-http-http-http/))

Either way, it would be nice to update the man page on `--remote-name` accordingly.

2023-01-21 11:10 UTC, vszakats commented
@Smackd0wn 👍 for URL-decoding and updating the man page.

The fragment trick example can be modified like these to keep copies of each download:
`curl -O 'https://example.com/index.html#[1-10]' --no-clobber` (needs 7.83.0)
`curl 'https://example.com/index.html#[1-10]' --output 'index.html##1'`

2023-05-16 08:52 UTC, bagder commented
Every bugfix is a behavior change, but this is one we want to stick with and it has not caused a lot of blow back.

2023-05-16 08:52 UTC, closed without merging